/*
 * PanelTablero - Muestra el tablero del juego como una grilla de botones
 */
package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 * Panel que renderiza un tablero 10x10 usando botones
 */
public class PanelTablero extends javax.swing.JPanel {

    // Matriz de botones para representar las 100 celdas del tablero
    private JButton[][] botones;

    /**
     * Constructor - Inicializa los componentes y crea la grilla
     */
    public PanelTablero() {
        initComponents();
        inicializarGrid();
    }

    /**
     * Inicializa la grilla de botones 10x10
     * Crea un botón para cada celda del tablero
     */
    private void inicializarGrid() {
        // Definir el layout como GridLayout de 10 filas x 10 columnas
        setLayout(new GridLayout(10, 10));

        // Inicializar la matriz de botones (10x10 = 100 botones)
        botones = new JButton[10][10];

        // Recorrer cada fila y columna para crear los botones
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {
                // Crear nuevo botón para esta celda
                botones[fila][col] = new JButton();

                // Establecer tamaño fijo para cada botón (40x40 píxeles)
                botones[fila][col].setPreferredSize(new Dimension(40, 40));

                // Agregar el botón al panel
                add(botones[fila][col]);
            }
        }
    }

    /**
     * Actualiza la visualización del tablero según el modelo
     * @param celdas Matriz de caracteres del tablero (~, B, O, X)
     * @param mostrarBarcos true = mostrar barcos, false = ocultar (tablero enemigo)
     */
    public void actualizarTablero(char[][] celdas, boolean mostrarBarcos) {
        // Recorrer todas las filas y columnas
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {
                // Obtener el valor de la celda actual
                char celda = celdas[fila][col];

                // Establecer el texto del botón según el contenido
                botones[fila][col].setText(String.valueOf(celda));

                // Establecer el color según el tipo de celda
                if (celda == '~') {
                    // Agua - azul claro
                    botones[fila][col].setBackground(new Color(173, 216, 230));
                } else if (celda == 'B') {
                    // Barco - gris (solo mostrar si mostrarBarcos = true)
                    if (mostrarBarcos) {
                        botones[fila][col].setBackground(Color.GRAY);
                    } else {
                        // Si es el tablero enemigo, ocultar como agua
                        botones[fila][col].setBackground(new Color(173, 216, 230));
                        botones[fila][col].setText("~");
                    }
                } else if (celda == 'X') {
                    // Impacto - rojo
                    botones[fila][col].setBackground(Color.RED);
                } else if (celda == 'O') {
                    // Agua disparada - azul oscuro
                    botones[fila][col].setBackground(Color.BLUE);
                }
            }
        }
    }

    /**
     * Agrega unActionListener a un botón específico para detectar clics
     * @param fila Fila del botón (0-9)
     * @param col Columna del botón (0-9)
     * @param listener ActionListener que maneja el clic
     */
    public void agregarListener(int fila, int col, java.awt.event.ActionListener listener) {
        botones[fila][col].addActionListener(listener);
    }

    /**
     * Agrega ActionListeners a todos los botones del tablero
     * @param listener ActionListener que maneja los clics
     */
    public void agregarListenerATodos(java.awt.event.ActionListener listener) {
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {
                botones[fila][col].addActionListener(listener);
            }
        }
    }

    /**
     * Obtiene la matriz de botones (útil para debugging o extensiones)
     * @return Matriz de JButton
     */
    public JButton[][] getBotones() {
        return botones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // NetBeans genera este código automáticamente
        // No modificar manualmente
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}